# Notebook 14 – Statistics in Machine Learning

Statistics is an important foundation of Machine Learning.

Statistics helps us:

- Understand data
- Clean data
- Handle missing values
- Detect outliers
- Create useful features
- Scale numerical data
- Evaluate models
- Understand relationships between variables
- Reduce dimensions
- Make predictions
- Build recommendation systems

## Topics Covered

1. Data Cleaning
2. Missing Value Handling
3. Outlier Detection
4. Feature Engineering
5. Feature Scaling
6. Data Normalization
7. Model Evaluation
8. Linear Regression
9. Logistic Regression
10. Naive Bayes
11. Clustering
12. Principal Component Analysis (PCA)
13. Recommendation Systems

# 1. Data Cleaning

## How Statistics is Used

Data cleaning is the process of finding and fixing problems in a dataset.

Statistics helps us identify:

- Incorrect values
- Unusual values
- Missing values
- Duplicate data
- Inconsistent data
- Incorrect data types
- Extreme values

We can use statistical measures such as:

- Mean
- Median
- Mode
- Standard deviation
- Minimum
- Maximum
- Quartiles

to understand the data before building a Machine Learning model.

## Example

Suppose we have:

Age:

22, 25, 24, 26, 200

The value 200 is unusual for an employee age and may need investigation.

## Why is it important?

Poor-quality data can lead to poor Machine Learning models.

Statistics helps us understand whether values are reasonable or unusual.

In [1]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "Age": [22, 25, 24, 26, 200],
    "Salary": [30000, 40000, 35000, 45000, 50000]
})

print(df.describe())

              Age       Salary
count    5.000000      5.00000
mean    59.400000  40000.00000
std     78.611704   7905.69415
min     22.000000  30000.00000
25%     24.000000  35000.00000
50%     25.000000  40000.00000
75%     26.000000  45000.00000
max    200.000000  50000.00000


# 2. Missing Value Handling

## How Statistics is Used

Machine Learning algorithms often cannot work directly with missing values.

Statistics can help us decide how to replace missing values.

Common methods include:

- Mean
- Median
- Mode

### Mean

Used when the numerical data is reasonably symmetric and not strongly affected by outliers.

### Median

Useful when the data is skewed or contains outliers.

### Mode

Commonly used for categorical data.

## Example

Salary:

30000, 35000, NaN, 40000, 45000

We can replace the missing value using the mean or median.

## Why is it important?

Handling missing values allows us to use the dataset for Machine Learning without simply discarding useful observations.

In [2]:
df = pd.DataFrame({
    "Salary": [30000, 35000, np.nan, 40000, 45000]
})

# Fill missing value with median
df["Salary"] = df["Salary"].fillna(df["Salary"].median())

print(df)

    Salary
0  30000.0
1  35000.0
2  37500.0
3  40000.0
4  45000.0


# 3. Outlier Detection

## How Statistics is Used

An outlier is a value that is unusually far from most other observations.

Statistics provides several methods for detecting outliers:

- IQR Method
- Z-Score Method
- Standard Deviation
- Box Plot

### IQR Method

IQR = Q3 - Q1

Values below:

Q1 - 1.5 × IQR

or above:

Q3 + 1.5 × IQR

are commonly flagged as potential outliers.

## Example

Salaries:

30000, 32000, 35000, 36000, 38000, 200000

200000 may be identified as a potential outlier.

## Why is it important?

Outliers can strongly affect:

- Mean
- Standard deviation
- Regression models
- Machine Learning performance

In [3]:
from scipy.stats import zscore

salary = np.array([30000, 32000, 35000, 36000, 38000, 200000])

z_scores = zscore(salary)

print(z_scores)

[-0.51472758 -0.48238867 -0.43388031 -0.41771086 -0.38537196  2.23407938]


# 4. Feature Engineering

## How Statistics is Used

Feature Engineering means creating new features from existing data.

Statistics helps us identify useful transformations and relationships.

Examples:

- Creating Age from Date of Birth
- Creating Total_Spend from multiple purchases
- Creating Average_Score
- Creating Income_per_Member
- Creating Ratios
- Log transformation for highly skewed variables

## Example

Suppose we have:

Monthly Income
Monthly Expenses

We can create:

Savings = Income - Expenses

This new feature may provide useful information to the model.

## Why is it important?

Good features can help a Machine Learning model identify useful patterns in the data.

In [4]:
df = pd.DataFrame({
    "Income": [30000, 40000, 50000],
    "Expenses": [20000, 25000, 30000]
})

df["Savings"] = df["Income"] - df["Expenses"]

print(df)

   Income  Expenses  Savings
0   30000     20000    10000
1   40000     25000    15000
2   50000     30000    20000


# 5. Feature Scaling

## How Statistics is Used

Feature Scaling changes numerical features to comparable scales.

This is important when features have very different ranges.

Example:

Age:

20 - 60

Salary:

20,000 - 200,000

Salary has much larger numerical values.

Some Machine Learning algorithms can be affected by these differences in scale.

Common scaling methods:

- Standardization
- Min-Max Scaling

## Standardization

Standardization transforms data using:

z = (x - mean) / standard deviation

After standardization, the feature has approximately:

Mean = 0
Standard deviation = 1

## When is it useful?

Scaling is especially important for algorithms such as:

- KNN
- K-Means
- SVM
- PCA
- Logistic Regression
- Linear Regression with regularization

In [5]:
from sklearn.preprocessing import StandardScaler

data = pd.DataFrame({
    "Age": [20, 25, 30, 35, 40],
    "Salary": [25000, 35000, 50000, 70000, 100000]
})

scaler = StandardScaler()

scaled_data = scaler.fit_transform(data)

print(scaled_data)

[[-1.41421356 -1.16014584]
 [-0.70710678 -0.78590525]
 [ 0.         -0.22454436]
 [ 0.70710678  0.52393683]
 [ 1.41421356  1.64665861]]



# 6. Data Normalization

## How Statistics is Used

Normalization usually means transforming values to a specific range, commonly 0 to 1.

A common Min-Max formula is:

X_scaled = (X - X_min) / (X_max - X_min)

After Min-Max scaling:

Minimum value → 0
Maximum value → 1

## Example

Original values:

10, 20, 30, 40, 50

After Min-Max scaling:

0, 0.25, 0.50, 0.75, 1

## Why is it useful?

Normalization can help algorithms that depend on distances or feature magnitude.

Examples:

- KNN
- K-Means
- Neural Networks
- Some optimization-based models

## Important

Normalization and Standardization are not exactly the same.

Normalization often refers to scaling to a fixed range such as 0 to 1.

Standardization transforms data based on mean and standard deviation.

In [6]:
from sklearn.preprocessing import MinMaxScaler

data = [[10], [20], [30], [40], [50]]

scaler = MinMaxScaler()

normalized_data = scaler.fit_transform(data)

print(normalized_data)

[[0.  ]
 [0.25]
 [0.5 ]
 [0.75]
 [1.  ]]


# 7. Model Evaluation

## How Statistics is Used

Statistics is used to measure how well a Machine Learning model performs.

For Regression, common metrics include:

- MAE
- MSE
- RMSE
- R²

For Classification, common metrics include:

- Accuracy
- Precision
- Recall
- F1-Score
- ROC-AUC

Statistics helps us determine whether model predictions are close to the actual values or whether classification predictions are correct.

## Why is it important?

A model that works well on training data may perform poorly on unseen data.

Statistical evaluation helps us measure model performance on data that the model did not train on.

## Example

Actual:

100, 200, 300

Predicted:

110, 190, 310

We can calculate the prediction error using metrics such as MAE or RMSE.

In [7]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

actual = [100, 200, 300]
predicted = [110, 190, 310]

mae = mean_absolute_error(actual, predicted)
mse = mean_squared_error(actual, predicted)
rmse = np.sqrt(mse)
r2 = r2_score(actual, predicted)

print("MAE:", mae)
print("MSE:", mse)
print("RMSE:", rmse)
print("R²:", r2)

MAE: 10.0
MSE: 100.0
RMSE: 10.0
R²: 0.985


# 8. Linear Regression

## How Statistics is Used

Linear Regression models the relationship between one or more independent variables and a continuous target.

The basic equation is:

y = b₀ + b₁x

Where:

- y = predicted value
- b₀ = intercept
- b₁ = coefficient
- x = input feature

Statistics is used to:

- Estimate coefficients
- Measure relationships between variables
- Analyze residuals
- Calculate R²
- Evaluate model errors
- Test assumptions

## Example

We can predict salary based on years of experience.

Experience → Salary

If experience increases, salary may also increase in the example dataset.

## Important Statistical Concepts

Linear Regression is closely related to:

- Mean
- Variance
- Covariance
- Correlation
- Least Squares
- Residuals
- R²

In [8]:
from sklearn.linear_model import LinearRegression

X = [[1], [2], [3], [4], [5]]
y = [30000, 40000, 50000, 60000, 70000]

model = LinearRegression()

model.fit(X, y)

prediction = model.predict([[6]])

print("Predicted Salary:", prediction[0])
print("Coefficient:", model.coef_[0])
print("Intercept:", model.intercept_)

Predicted Salary: 80000.0
Coefficient: 10000.0
Intercept: 20000.0


# 9. Logistic Regression

## How Statistics is Used

Logistic Regression is mainly used for classification problems.

It predicts the probability of a class.

For example:

Customer → Will Buy / Will Not Buy

Statistics is used to model probabilities using the logistic function.

The model converts a linear combination of features into a probability between 0 and 1.

## Example

Suppose we want to predict whether a customer will purchase a product based on age.

Age → Purchase Probability

If the probability is greater than a chosen classification threshold, such as 0.5, we may classify the customer as "Purchase".

## Statistics Used

- Probability
- Log-odds
- Maximum likelihood estimation
- Probability distributions
- Classification metrics

The threshold can be changed depending on the business problem.

In [9]:
from sklearn.linear_model import LogisticRegression

X = [[20], [25], [30], [35], [40], [45]]
y = [0, 0, 0, 1, 1, 1]

model = LogisticRegression()

model.fit(X, y)

probability = model.predict_proba([[32]])

print("Probability:", probability)
print("Prediction:", model.predict([[32]]))

Probability: [[0.59145146 0.40854854]]
Prediction: [0]


# 10. Naive Bayes

## How Statistics is Used

Naive Bayes is a classification algorithm based on Bayes' Theorem.

It calculates the probability of a class given observed features.

The basic idea is:

P(Class | Features)

The algorithm uses:

- Prior probability
- Likelihood
- Posterior probability

## Example

In spam detection:

Email features → Spam / Not Spam

The model can estimate:

P(Spam | Words in Email)

For example, words such as "offer", "winner", or "free" may provide evidence that an email belongs to the spam class.

## Why is it called "Naive"?

It assumes that features are conditionally independent given the class.

This assumption is often unrealistic, but the method can still work well for some tasks.

## Common Applications

- Spam detection
- Text classification
- Sentiment classification
- Document classification

In [10]:
from sklearn.naive_bayes import GaussianNB

X = [
    [1, 20],
    [2, 25],
    [3, 30],
    [8, 40],
    [9, 45],
    [10, 50]
]

y = [0, 0, 0, 1, 1, 1]

model = GaussianNB()

model.fit(X, y)

prediction = model.predict([[4, 32]])

print("Prediction:", prediction)

Prediction: [0]


# 11. Clustering

## How Statistics is Used

Clustering is an unsupervised learning technique that groups similar observations together.

Statistics helps us understand:

- Distance
- Mean
- Variance
- Cluster centers
- Within-cluster variation
- Between-cluster differences

## Example

An e-commerce company can group customers based on:

- Age
- Income
- Spending

Possible groups:

- Low spending customers
- Medium spending customers
- High spending customers

## K-Means

K-Means calculates cluster centers called centroids.

Each observation is assigned to the nearest centroid.

The algorithm attempts to minimize the variation within clusters.

## Common Applications

- Customer segmentation
- Market segmentation
- Image grouping
- Pattern discovery

In [11]:
from sklearn.cluster import KMeans

X = [
    [20, 2000],
    [22, 2500],
    [25, 3000],
    [40, 7000],
    [42, 7500],
    [45, 8000]
]

model = KMeans(
    n_clusters=2,
    random_state=42,
    n_init=10
)

model.fit(X)

print("Cluster Labels:")
print(model.labels_)

print("Cluster Centers:")
print(model.cluster_centers_)

Cluster Labels:
[0 0 0 1 1 1]
Cluster Centers:
[[  22.33333333 2500.        ]
 [  42.33333333 7500.        ]]


# 12. Principal Component Analysis (PCA)

## How Statistics is Used

PCA is a dimensionality-reduction technique.

It transforms many correlated features into a smaller number of new variables called **Principal Components**.

Statistics used in PCA includes:

- Mean
- Variance
- Covariance
- Covariance Matrix
- Eigenvalues
- Eigenvectors

## Main Idea

Suppose we have:

10 features

PCA may transform them into:

2 principal components

while retaining a large amount of the variation in the original data.

## Why is PCA useful?

PCA can help:

- Reduce the number of features
- Reduce computational complexity
- Visualize high-dimensional data
- Remove some redundant information
- Reduce noise in some situations

## Important

PCA is sensitive to feature scale, so features are often standardized before applying PCA.

In [12]:
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

X = [
    [10, 100],
    [20, 200],
    [30, 300],
    [40, 400],
    [50, 500]
]

# Step 1: Standardize
scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)

# Step 2: Apply PCA
pca = PCA(n_components=1)

X_pca = pca.fit_transform(X_scaled)

print("Original shape:", np.array(X).shape)
print("New shape:", X_pca.shape)

print("Transformed data:")
print(X_pca)

print("Explained variance ratio:")
print(pca.explained_variance_ratio_)

Original shape: (5, 2)
New shape: (5, 1)
Transformed data:
[[-2.]
 [-1.]
 [ 0.]
 [ 1.]
 [ 2.]]
Explained variance ratio:
[1.]


# 13. Recommendation Systems

## How Statistics is Used

Recommendation systems use data about users and items to predict what a user may prefer.

Examples:

- Netflix movie recommendations
- Amazon product recommendations
- Spotify music recommendations
- YouTube video recommendations

Statistics helps analyze:

- User behavior
- Ratings
- Purchase history
- Clicks
- Views
- Similarity
- Probabilities
- Average ratings

## Example

Suppose users rate movies:

User A:

Movie 1 → 5
Movie 2 → 4
Movie 3 → 5

User B:

Movie 1 → 5
Movie 2 → 4

Because User A and User B have similar rating patterns, the system may recommend Movie 3 to User B.

## Common Statistical Concepts

- Mean ratings
- Correlation
- Similarity
- Probability
- Distributions
- Collaborative filtering

## Types of Recommendation Systems

### 1. Content-Based Filtering

Recommends items similar to items the user already likes.

### 2. Collaborative Filtering

Uses similarities between users or items.

### 3. Hybrid Systems

Combine multiple recommendation approaches.

In [13]:
import pandas as pd

ratings = pd.DataFrame({
    "User": ["A", "A", "A", "B", "B"],
    "Movie": ["Movie1", "Movie2", "Movie3", "Movie1", "Movie2"],
    "Rating": [5, 4, 5, 5, 4]
})

print(ratings)

# Calculate average rating for each movie
average_rating = ratings.groupby("Movie")["Rating"].mean()

print("\nAverage Rating:")
print(average_rating)

  User   Movie  Rating
0    A  Movie1       5
1    A  Movie2       4
2    A  Movie3       5
3    B  Movie1       5
4    B  Movie2       4

Average Rating:
Movie
Movie1    5.0
Movie2    4.0
Movie3    5.0
Name: Rating, dtype: float64


# Statistics in Machine Learning – Summary

| Machine Learning Area | How Statistics is Used |
|---|---|
| Data Cleaning | Understand data quality and unusual values |
| Missing Value Handling | Use mean, median, or mode |
| Outlier Detection | Use IQR, Z-score, standard deviation |
| Feature Engineering | Create useful statistical features |
| Feature Scaling | Use mean and standard deviation |
| Data Normalization | Transform values to a common range |
| Model Evaluation | Calculate errors and performance metrics |
| Linear Regression | Estimate relationships and coefficients |
| Logistic Regression | Estimate class probabilities |
| Naive Bayes | Calculate probabilities using Bayes' theorem |
| Clustering | Measure similarity, distance, and variation |
| PCA | Use covariance, variance, eigenvalues, and eigenvectors |
| Recommendation Systems | Analyze ratings, similarity, and user behavior |


# Key Takeaways

1. Statistics helps us understand and clean data before Machine Learning.

2. Mean, median, mode, variance, standard deviation, and percentiles are useful for data analysis.

3. IQR and Z-score can help identify potential outliers.

4. Scaling and normalization help algorithms work effectively when features have different scales.

5. Regression models use statistical relationships between variables.

6. Logistic Regression and Naive Bayes use probability to perform classification.

7. Clustering uses concepts such as distance, means, and variation to group similar observations.

8. PCA uses variance and covariance to reduce dimensions.

9. Model evaluation uses statistical metrics to measure prediction performance.

10. Recommendation systems use statistics to analyze user behavior, ratings, similarity, and preferences.

### Final Idea

Statistics helps Machine Learning answer three important questions:

- What does the data look like?
- What patterns exist in the data?
- How reliable are the model's results?